# 项目名称、版本、版权年份
rzspider:
  name: RZSpider
  version: 3.3.0
  copyrightYear: 2019
  #头像地址
  profile: C:\profile\

#开发环境配置
server:
  #端口
  port: 8888
  tomcat:
    uri-encoding: utf-8
#日志配置
logging:
  level:
    com.rzspider: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
#用户配置
user:
  password:
    #密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 3
#Spring配置
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  messages:
    #国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  http:
    multipart:
      max-file-size: 500Mb
      max-request-size: 500Mb
  devtools:
    restart:
      enabled: true    
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.rzspider
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
# PageHelper
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEbabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
# 代码生成
gen: 
  # 作者
  author: ricozhou
  # 默认生成包路径 module 需改成自己的模块名称 如 system monitor tool
  packageName: com.rzspider.project.blog
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀(类名不会包含表前缀)
  tablePrefix: sys_
# 文件数据存放地址（注意都是文件夹且最后都没有斜杠，都是收尾不带斜杆,请注意不要只留盘符，系统自带清理，容易误删）
filepath:
  #基础数据路径(必填)
  basePath: rzspider
  # java编译器所在位置（tool.jar目录）(不填则默认系统编译器)(选填)
  javaCompilerPath: 
  # java运行环境（jre）所在位置（jre目录）（不填则使用系统java环境）(选填)
  jreRunPath: 
  # nodejs运行环境（nodejs）所在位置（js自定义爬虫需要，不填则使用系统nodejs环境，最好使用安装版，否则部分功能受限）(选填)
  nodeJSRunPath: 
  # Python运行环境（Python）所在位置（Python自定义爬虫需要，不填则使用系统Python环境，最好使用安装版，否则部分功能受限）(选填)
  pythonRunPath: 